version: '3.9'


services:
  db:
    build: .
    restart: always
    ports: 
      - "5433:5432"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME_TEST}
      POSTGRES_USER: ${DB_USERNAME}
    container_name: librarydb_test
   