name: LibrayBooks

on:
  push:
    branches: 
      - JoseLuis
  pull_request:
    branches:
      - JoseLuis
jobs:
    libraryBooks:
      runs-on: ubuntu-22.04
      steps: 
        - name: Echo the message
          run: |
            echo "Hola chaval"
        - name: Dime la fecha
          run: date
        - run: ls-l 