name: Books

on:
  push:
    branches:
      - JoseLuis
  pull_request:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-22.04          
    steps:
      - uses: actions/checkout@v2
        with: 
          fetch-depth: 0
      - uses: actions/setup-node@v2
        with:
          node-version: '16.17.1'
      - name: Install dependencies
        run:  yarn install --no audit --no fund --no-optional
      - name: Lint
        run: yarn run eslint
      - name: Build
        run: yarn build
      - uses: actions/upload-artifact@v3
        with:
          name: dist
          path: dist  
      

  TestE2e:
    needs: [Dependencias]
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 16.x
          cache: yarn
      - name: Installs dependencias
        run: yarn --frozen-lockfile
      - uses: actions/download-artifact@v3
        with:
          name: dist
          path: dist
      - name: TEST e2e 
        run: yarn test    